### ISSUE TITLE
uos.getcwd: Device stalls when calling getcwd

### ISSUE THREAD

**Issue by robert-hh** [WinnerMicro/micropython#1]
OS version:MicroPython v1.10-284-g2eee4e2-dirty on 2019-11-08; WinnerMicro module with W600
Image: Downloaded from http://www.winnermicro.com/en/upload/1/editor/1573450100756.zip
Device: TB-01, 1 MByte flash
Error: When executing after boot from REPL:
```
import uos
uos.getcwd()
```
the device stalls an can only be revived with reset. 
Even when setting the CWD after boot to /flash or setting the CWD in main.c, problems with littlefs persist. File operations sometimes fail, sometimes the file system seems to disappear, sometimes new files are created with additikonal characters in their name. That all points at memory allocation or pointer errors in the driver or driver interface. Replacing the core littelfs files with the most recent ones did not change the issue.
Edit: I see that Tabao also offers 2MB modules. But I cannot read the page. Aliexpress only shows 1 MB modules.

**Comment by robert-hh** [comment]
I have  short test script which also has the tendency to fail:
```
import os
LINES = const(400)
cwd = "/flash"
fname = "testfile.txt"

def make_file(fname):
    with open(fname, "w") as f:
        for i in range(LINES):
            l = ("%03d *" % i) + (os.urandom(1)[0] % 64) * '*'
            f.write(l + '\n')
    print(LINES, "lines written to ", fname)

os.chdir(cwd)
print(os.listdir())
make_file(fname)
print(os.listdir())
```
It fails at the second os.listdir(). Log while running:
```
>>> import fst
['boot.py', 'fs_test.py', 'fst.py', 'main.py', 'testfile.txt']
400 lines written to  testfile.txt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fst.py", line 16, in <module>
OSError: [Errno 2] ENOENT
```
Sometimes is passes. Sometimes the file system gets corrupt. That script works with FAT, and it works on Micropython.org devices with Littlefs.

MicroPython v1.10-284-g2eee4e2-dirty on 2019-11-08; WinnerMicro module with W600

**Comment by robert-hh** [comment]
I'm tracing it further. It looks like an issue i have seen also with Pycom boards, in that locally used buffers are allocated using gc_alloc or m_malloc or as Python objects. If they do not belong to python objects, garbage collection will free them, causing memory chaos. As a test, I modified my test script.
```
import os
import gc
LINES = const(10)
cwd = "/flash"
fname = "testfile.txt"

def make_file(fname, lines):
    with open(fname, "w") as f:
        for i in range(lines):
            l = ("%03d *" % i) + (os.urandom(1)[0] % 64) * '*'
            f.write(l + '\n')
    print(LINES, "lines written to ", fname)

def run(lines=LINES):
    print(gc.mem_free())
    os.chdir(cwd)
    print(os.listdir())
    make_file(fname, lines)
    print(os.listdir())
    print(gc.mem_free())
```
The result when calling it a few timer after boot & load:
```
>>> import fst
>>> fst.run(10)
29536
['boot.py', 'fst.py', 'main.py', 'testfile.txt']
400 lines written to  testfile.txt
['boot.py', 'fst.py', 'main.py', 'testfile.txt']
22416
>>> fst.run(10)
22352
['boot.py', 'fst.py', 'main.py', 'testfile.txt']
400 lines written to  testfile.txt
['boot.py', 'fst.py', 'main.py', 'testfile.txt']
15152
>>> fst.run(10)
15088
['boot.py', 'fst.py', 'main.py', 'testfile.txt']
400 lines written to  testfile.txt
['boot.py', 'fst.py', 'main.py', 'testfile.txt']
7728
>>> fst.run(10)
7664
['boot.py', 'fst.py', 'main.py', 'testfile.txt']
400 lines written to  testfile.txt
['boot.py', 'fst.py', 'main.py', 'testfile.txt']
752
>>> fst.run(10)
assertion "ATB_GET_KIND(block) == AT_HEAD" failed: file "../../py/gc.c", line 588, function: gc_free

```
You can see, that free memory decreases until during the last call garbage collection steps in, causing MP to fail with a strange error. You can provoke an error earlier by calling gc.collect() manually. While I was assuming thatz reason all the time, I simply do not find the wrong allocation which causes that trouble. Since vfs and littlefs are literally identical to other ports in which they work, the difference is only main.c or hal/modflash.c.

**Comment by robert-hh** [comment]
After staring at the differences between FAT and littlefs and comparing it to other builds w/o seeing any difference, I uses that test script with FAT again. After repeating the test more often, it fails too. So the difference is not the file system, but something else.

**Comment by robert-hh** [comment]
Fixing the getcwd() freeze is easy. Just set the initial directory during/after boot, either in main.c or in _boot.py. But that does not solve the crashes, which are some kind of memory corruption. But I cannot find the reason. There seem to be some inconsistencies in setting the stacks for threads, but more like unfinished work than errors. And I am not sure whether gccollect.c is really implemented right, especially when defining the areas which is searched for root pointers.

**Comment by robert-hh** [comment]
So I fixed both the getwcd() freeze and the strange behavior of the file system after garbage collect. Both changes are in main.c. I cannot make a PR, because git does not allow me to fork from the winnermicro fork without creating a new account. So I have attached the file here. 
[main.zip](https://github.com/WinnerMicro/micropython/files/4466323/main.zip)
There is also a small change to the mp_thread_init() call. The corresponding change in the file mpthreadport.c is attached. But that is just for consistency. The resulting behavior is not changed.
[mpthreadport.zip](https://github.com/WinnerMicro/micropython/files/4466331/mpthreadport.zip)

**Comment by wdyichen** [comment]
Thanks for your help, I will update your changes later

**Comment by robert-hh** [comment]
I have a question about the SPI flash sector size of the W600. The data sheet does not mention it. In the Littlefs settings I have reduced the sector size to 512 bytes. That works well, and leads to a drastically reduced RAM allocation. littlefs allocates at least 3 buffers of sector size. at 4K, this is 12k. Using 512 bytes sectors, this is <1k. Since also each file uses at least one sector, and a directory 2, the number of files in the given 48k file system would be restricted to 12. Reducing the sector size make the file system much more useful. The sector size does not have to be larger than the page size of the underlying flash device.

**Comment by wdyichen** [comment]
@robert-hh The WMSDK flash driver operates a 4k sector every time. If the power is interrupted during the operation, the data on the 4K sector will be lost, which is actually very disadvantageous to LittleFS.

**Comment by robert-hh** [comment]
Thanks. Still, using 512byte sectors with littlefs works. Di you know the place of the WMSDK documentation?

**Comment by robert-hh** [comment]
I found the file wm_internal_flash.h, which tells, that the sector size is 4k, but the page size is 256 byte. That should be the smallest logical sector size for a file system.

**Comment by wdyichen** [comment]
It is definitely usable, but it is not safe. Because the WMSDK driver operates 4K at a time, the risk here is relatively large.
The current official document is http://www.winnermicro.com/en/html/1/156/158/497.html, click "Technical documentation".
Sorry, you can only find out for yourself if there is no official document.

**Comment by wdyichen** [comment]
@robert-hh In addition, the 2M Flash module is only available in China. At present, only the courier company (DHL or Fedex ...) is available for purchasing, or you can apply for free samples on the official website (http://www.winnermicro.com/en/html/1/93/95/index.html).

**Comment by robert-hh** [comment]
Sadly enough, the change I made in main.c at the start of init_spiflash() by calling m_new_obj_maybe() instead of tls_mem_alloc() does not fix all problems. There is one which still occurs, but more rare. In my test code it happens if before calling the free memory is very low, like < 400 bytes. And it only happens if this code is called repeatedly from the command line. If it is called in a programmed loop, everything is stable. So there might have been two errors. The error I get is:
```
assertion "ATB_GET_KIND(block) == AT_HEAD" failed: file "../../py/gc.c", line 588, function: gc_free
```

The other error about a unusable file system did not occur any more in all tests. That one reappears if I use tls_mem_alloc() in that line:
```
    spi_fls_vfs = m_new_obj_maybe(fs_user_mount_t);
```
Edit: The memory problem mentioned here is not likely to happen in newer versions of MP, since the memory handling was changed. Garbage collection happens much earlier. So moving to the actual version of MicroPython is wishful.

**Comment by robert-hh** [comment]
That seemed too easy:
```
MicroPython v1.12-375-gc462d5f5c-dirty on 2020-04-15; WinnerMicro module with W600
Type "help()" for more information.
```
Even the files size got lower. There must be serious problems under the hood.
Edit: The gc error still persists, only one can make it happen earlier.

**Comment by robert-hh** [comment]
I close this one, since the getcwd() issue is successully addressed, and as well the cooupted lfs issue.
I'll open a new one on the gc.free() assert fail.
