### ISSUE TITLE
_thread: Unclear whether it works [some progress]

### ISSUE THREAD

**Issue by robert-hh** [WinnerMicro/micropython#3]
I tried a simple threading example, and it does not seem to work. Did you ever had it working, and do you have an example script available? The examples I used with other ports do not work.

**Comment by robert-hh** [comment]
Tracing it through the calls, it stops at the call to MP_THREAD_GIL_ENTER(); in the function thread_entry() in py/modthread.c. Which means, that the thread is set up, but waiting for the GIL to be released.
Edit: The reason may be here in mpconfigport.h:
```
#define MICROPY_EVENT_POLL_HOOK \
    do { \
        extern void mp_handle_pending(void); \
        mp_handle_pending(); \
        MP_THREAD_GIL_EXIT(); \
        MP_THREAD_GIL_ENTER(); \
    } while (0);
```
I other ports there is a scheduler invoked between MP_THREAD_GIL_EXIT() and MP_THREAD_GIL_ENTER(), to allow other threads to run.

**Comment by robert-hh** [comment]
Inserting a small delay causes the other thread to execute:
```
#define MICROPY_EVENT_POLL_HOOK \
    do { \
        extern void mp_handle_pending(void); \
        mp_handle_pending(); \
        MP_THREAD_GIL_EXIT(); \
        tls_os_time_delay(1); \
        MP_THREAD_GIL_ENTER(); \
    } while (0);
```
That's a first step to make it work.
Edit: Even after some trials, this does not work well. I can start a second thread, and it runs in parallel to the main thread. But as soon as it stops, the board freezes most of the time. Could be a memory problem, or a lock problem.
Nevertheless, with V1.12 uasyncio works well, which is anyhow preferred over threading for small devices.

**Comment by robert-hh1** [comment]
I made a PR for a working _thread module.
