### ISSUE TITLE
w600: Call the ROM bootloader from User space.

### ISSUE THREAD

**Issue by robert-hh** [WinnerMicro/micropython#31]
@wdyichen I do not know if you are still active of listing on that repository. I have a question:

Is it possible to call/start the ROM bootloader from user space code? Like by setting a flag in a register or RAM and performing reset.

**Comment by wdyichen** [comment]
> @wdyichen I do not know if you are still active of listing on that repository. I have a question:
> 
> Is it possible to call/start the ROM bootloader from user space code? Like by setting a flag in a register or RAM and performing reset.

I don't quite understand what you mean, should I restart the chip?
w60x usually uses the watchdog to reset the chip, you can refer to the API in the SDK: tls_sys_reset, which is to configure the register to reset the chip.

**Comment by robert-hh** [comment]
Thank you for your swift reply. The intention is to implement machine.bootloader(), which, when called, starts the chip's bootloader. I know tls_sys_reset(), but that just resets the chip and does not run the ROM bootloader. It may activate the bootloader in the secboot image, but not the one from the ROM firmware, which gets active when PA0 is low at Reset. Only, some boards do not expose the PA0 pin.

**Comment by wdyichen** [comment]
> Thank you for your swift reply. The intention is to implement machine.bootloader(), which, when called, starts the chip's bootloader. I know tls_sys_reset(), but that just resets the chip and does not run the ROM bootloader. It may activate the bootloader in the secboot image, but not the one from the ROM firmware, which gets active when PA0 is low at Reset. Only, some boards do not expose the PA0 pin.

I see what you mean, I did some research and found a way.

The startup sequence of w60x is rom--->bootloader(secboot)--->userapp.
The rom can only detect pa0 to enter, and the rom only supports working on uart0, and the firmware file used is *.fls.
secboot can only detect the esc key to enter, secboot can work on uart0 and uart1, and the firmware file used is *.img.

I think redoing a secboot version is the easiest way to achieve this goal, but the maintenance of the secboot version will be another problem, which is not easy to deal with at present.

Therefore, currently only the functions provided by rom can be used, and the usage process is as follows:
When executing machine.bootloader(), find a space on the flash to mark, and then restart (ex. tls_sys_reset()).
Next, check in the main function. When you find that the flash has this flag, clear the flag, and then execute the following code to enter the rom download mode:
```
typedef void (*rom_func_dlfw)(int, int);
rom_func_dlfw enter_rom_dlfw = (rom_func_dlfw)0x1B17;
enter_rom_dlfw(0, 0);
```
Note: Be sure to operate at the very beginning of the main function entry (wm_main.c).

The rom download mode uses the xmodem protocol to transfer the *.fls firmware file. After the transfer is completed, the device needs to be manually reset to start the firmware.

**Comment by robert-hh** [comment]
Thank you very much. I'll try that.

**Comment by robert-hh** [comment]
Thanks a lot. It works like a charm. I used a magic number in RAM instead of flash. There may be false triggers, but these should be rare and cleared after a reset.

**Comment by wdyichen** [comment]
This is a very good idea, simple and easy to use.
