### ISSUE TITLE
Micropython 1.12: Not an issue

### ISSUE THREAD

**Issue by robert-hh** [WinnerMicro/micropython#5]
I have build the w600 port with Micropython 1.12. Thanks to the excellent work of @wdyichen, this was easy. Just a few lines of code (2 or 3?) had to be changed. At first glance, it works the same, whether good or bad. The ports/w60x directory sits just aside the usual MP file tree, so it can easily be added for testing in anyone's own file tree. There is still a lot open to do:

- TESTING
- remove the shortcuts & hacks
- define and use BOARD for the various boards available
- include the manifest mechanisms for scripts.

Link here: https://github.com/robert-hh/micropython/tree/w60x

**Comment by paulhayes** [comment]
Hi @robert-hh thanks for doing this! The WinnerMicro fork of micropython seems to have been abandoned for a while. Would you still recommend your fork for building new versions of the W600-pico firmware?

**Comment by robert-hh** [comment]
Hi @paulhayes. Thank you for the interest. @e-tobi and me try to keep this branch as close as possible to the main micropython.org version. The WinnerMicro fork is silent since a while, and the maintainer does not respond. So yes, you can use my fork. I can also update the binary images which I have at https://github.com/robert-hh/Shared-Stuff.
Edit: I updated my branch to today's state of the micropython repository.

**Comment by paulhayes** [comment]
Oh wow, thanks for putting your builds up! That's great. Will these work on the 1MB w600-pico by wemos?

**Comment by robert-hh** [comment]
They are made for 1MB boards. The 2MB boards seem not to be available.
